name: Extract Inputs

on:
  pull_request:
    types: [opened, edited]

jobs:
  extract-inputs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Org and Repo Name
      id: extract
      run: |
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        ORG_NAME=$(echo "$PR_BODY" | grep -oP '(?<=Org Name: ).*')
        REPO_NAME=$(echo "$PR_BODY" | grep -oP '(?<=Repo Name: ).*')
        echo "ORG_NAME=$ORG_NAME" >> $GITHUB_ENV
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Display extracted inputs
      run: |
        echo "Org Name: ${{ env.ORG_NAME }}"
        echo "Repo Name: ${{ env.REPO_NAME }}"
