name: Extract Inputs

on:
  pull_request:
    types: [opened, edited]

jobs:
  extract-inputs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq
      
    - name: Debug PR Body
      run: |
        echo "PR Body:"
        cat $GITHUB_EVENT_PATH
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        echo "$PR_BODY"

    - name: Extract Organization Username and Repository Name
      run: |
          ORG_USERNAME=$(echo "${{ github.event.pull_request.body }}" | grep -oP 'Org Name:.*?\[(.*?)\]' | cut -d '[' -f 2 | cut -d ']' -f 1)
          REPO_NAME=$(echo "${{ github.event.pull_request.body }}" | grep -oP 'Repo Name:.*?\[(.*?)\]' | cut -d '[' -f 2 | cut -d ']' -f 1)
          echo "::set-output name=org_username::$ORG_USERNAME"
          echo "::set-output name=repo_name::$REPO_NAME"
    
    - name: Display extracted inputs
      run: |
        echo "Org Name: ${{ env.ORG_USERNAME }}"
        echo "Repo Name: ${{ env.REPO_NAME }}"
